name: iOS starter workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      # - name: check scheme
      #   run: |
      #     cd Example

      # - name: check scheme
      #   run: |
      #     xcodebuild -list

      # - name: check directory
      #   run: |
      #     ls

      # - name: build archive
      #   run: |
      #     xcodebuild -scheme "Alamofire iOS" \
      #     -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
      #     -sdk iphoneos \
      #     -configuration Debug \
      #     -destination generic/platform=iOS \
      #     clean archive          



      - name: Build
        run: xcodebuild -scheme "Alamofire iOS" -sdk iphonesimulator

      - name: Archive
        run: xcodebuild archive -scheme "Alamofire iOS" -sdk iphonesimulator -archivePath ${{ github.workspace }}/build/Alamofire.xcarchive

      - name: Export Archive
        run: xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/Alamofire.xcarchive -exportPath ${{ github.workspace }}/build -exportOptionsPlist ExportOptions.plist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Alamofire-build
          path: ${{ github.workspace }}/build
